### ISSUE TITLE
Create a constructor with a float

### ISSUE THREAD

**Issue by LGHTNNG** [memio/spec-gen#10]
The following spec
```php
class TestSpec extends ObjectBehavior
{
    function it_floats()
    {
        $aFloat = 3.44;
        $this->beConstructedWith($aFloat);
        $this->floatMe()->shouldReturn($aFloat);
    }
}
```
generates the following class: 
```php
use float;

class Test
{
    private $argument;

    public function __construct(float $argument)
    {
        $this->argument = $argument;
    }
}
```
which generates the following error: 
`PHP Fatal error:  Cannot use float as float because 'float' is a special class name in /var/www/test/src/Test.php on line 5`

**Comment by ItsKelsBoys** [comment]
Looks like we also have dependency issues on php 7.0

**Comment by ItsKelsBoys** [comment]
Looks like phpunit is causing the php7.0 build to fail should we lower the phpunit version?

**Comment by gnugat** [comment]
Hi @ItsKelsBoys, thanks for your contribution!

However I'd rather go with a fix that makes `$fullyQualifiedName->getFullyQualifiedName();` return `double`: as you can see `GenerateConstructorHandler::NON_OBJECT_TYPES` doesn't contain `integer` and `boolean`, because I decided to go with `int` and `bool` only.

I'd like to continue favouring `double` over `float`, do you think you could identify and fix the issue in `FullyQualifiedName` instead?

Also, Travis is failing because phpunit 7 isn't compatible with PHP 7.0. Rather than having to choose between bumping the minimum version of spec-gen to 7.1 or tolling back to PHPUnit 6, this can be fixed by changing dependency on PHPUnit to `^6.0 || ^7.0`: when the Travis build runs on PHP 7.0, it will install PHPUnit 6, and when it runs on PHP 7.1, it will install PHPUnit 7.

**Comment by LGHTNNG** [comment]
Sure.

**Comment by LGHTNNG** [comment]
If things should be done differently let me know (im new to all of this) your guidance is desired and much appreciated :)

P.S
Started reading your blog its awesome :)

**Comment by gnugat** [comment]
We had a first fix for that exact same issue a while ago, but it looks like we missed a few edge case. Now thanks to you it's definitely fixed!

You did a perfect job, thank you very much for contributing :+1:

P.S thanks! I should probably start updating it again :thinking:
